---
- name: Delete tacacs user
  fortinet.fortios.fortios_user_tacacsplus:
    access_token: "{{ token }}"
    vdom: "{{ vdom }}"
    state: absent
    user_tacacsplus:
      name: "{{ item }}"
  loop: "{{ return_list.return_list | difference(tacacs.keys()) }}"
  loop_control:
    label: "{{ item }}"
