---
- name: Differ for /user/tacacs+/
  ansible.builtin.include_role:
    name: differ
  vars:
    differ_api_path: "user"
    differ_api_name: "tacacs+"
- name: Include Tasks
  ansible.builtin.include_tasks: add_tacacs.yml
- name: Include Tasks
  ansible.builtin.include_tasks: del_tacacs.yml
