---
- name: Differ for /firewall/address/
  ansible.builtin.include_role:
    name: differ
  vars:
    differ_api_path: "firewall"
    differ_api_name: "address"
- name: Include Tasks
  ansible.builtin.include_tasks: add_address.yml
- name: Include Tasks
  ansible.builtin.include_tasks: del_address.yml
