---
- name: Differ for /rotuer/access-list/
  ansible.builtin.include_role:
    name: differ
  vars:
    differ_api_path: "router"
    differ_api_name: "access-list"
- name: Include Tasks
  ansible.builtin.include_tasks: add_access_list.yml
- name: Include Tasks
  ansible.builtin.include_tasks: del_access_list.yml
