---
- name: Differ for /firewall.service/group/
  ansible.builtin.include_role:
    name: differ
  vars:
    differ_api_path: "firewall.service"
    differ_api_name: "group"
- name: Include Tasks
  ansible.builtin.include_tasks: add_service_group.yml
- name: Include Tasks
  ansible.builtin.include_tasks: del_service_group.yml
