---
- name: Differ for /router/static/
  ansible.builtin.include_role:
    name: differ
  vars:
    differ_api_path: "router"
    differ_api_name: "static"
- name: Include Tasks
  ansible.builtin.include_tasks: add_route.yml
- name: Include Tasks
  ansible.builtin.include_tasks: del_route.yml
