---
- name: Differ for /firewall/addrgrp/
  ansible.builtin.include_role:
    name: differ
  vars:
    differ_api_path: "firewall"
    differ_api_name: "addrgrp"
- name: Include Tasks
  ansible.builtin.include_tasks: add_addrgrp.yml
- name: Include Tasks
  ansible.builtin.include_tasks: del_addrgrp.yml
