---
- name: Add service
  fortinet.fortios.fortios_firewall_service_custom:
    access_token: "{{ token }}"
    vdom: "{{ vdom }}"
    state: present
    firewall_service_custom:
      category: "{{ item.value.category }}"
      comment: "{{ item.value.comment }}"
      iprange: "{{ item.value.iprange }}"
      name: "{{ item.key }}"
      protocol: "{{ item.value.protocol }}"
      tcp_portrange: "{{ item.value.tcp_portrange | default(omit) }}"
      udp_portrange: "{{ item.value.udp_portrange | default(omit) }}"
      visibility: "{{ item.value.visibility | default(omit) }}"
  loop: "{{ lookup('dict', custom, wantlist=True) }}"
  loop_control:
    label: "{{ item.key }}"
